name             'drupal_s3fs_proxy'
maintainer       'Maciek Ruckgaber'
maintainer_email 'maciekrb@gmail.com'
license          'All rights reserved'
description      'Installs/Configures Drupal drupal_s3fs proxy requests for CSS/JSS'
long_description 'Installs/Configures drupal_s3fs_proxy'
version          '0.1.0'
